### ISSUE TITLE
README out of date?

### ISSUE THREAD

**Issue by randroid88** [thisisartium/gpt_agent#12]
The configuration section of the README says:

> Replace `your-openai-api-key` with your actual OpenAI API key and
> `your-default-assistant-id` with the ID of your default assistant.

But the config example doesn't have `your-openai-api-key` or `your-default-assistant-id`

```elixir
config :open_ai_client, :base_url, System.get_env("OPENAI_BASE_URL") || "https://api.openai.com"
config :open_ai_client, :openai_api_key, System.get_env("OPENAI_API_KEY") || raise("OPENAI_API_KEY is not set")
config :open_ai_client, :openai_organization_id, System.get_env("OPENAI_ORGANIZATION_ID")
config :gpt_agent, :heartbeat_interval_ms, if(config_env() == :test, do: 1, else: 1000)
```

I may be missing something.

**Comment by jwilger** [comment]
Thanks! Yeah, I most likely need to update that.
